# The messages displayed on the bossbar
titles:
  - "Welcome to the server!"
  - "Don't forget to vote!"
  - "Use /kit to claim a kit!"

# The boss bar health
# min 0.0 max 1.0
percentage: 1.0

# The interval between each title in seconds
change-speed: 10

# Change the color of the bossbar
# Available colors:
# - PINK
# - BLUE
# - RED
# - GREEN
# - YELLOW
# - PURPLE
# - REBECCA_PURPLE
# - WHITE
color: "PURPLE"